### ISSUE TITLE
Planning

### ISSUE THREAD

**Issue by ivarconr** [ivarconr/ws-node-intro#1]
**Pre-req for deltakere:**
- Node v. 6
- npm v. 3
- En IDE du liker (IntelliJ IDEA, Atom.io, Sublime, Visual Studio Code, el.l)
- (docker)
## Intro oppgaver før lunsj:
- [x] Booke lokale Tirsdag 11.oktober 2016 til 20 personer (@ivarconr)
- [x] Lage en oppgaveliste @ivarconr
- [x] Skrive invitasjon / snakke med områdeledere (@ivarconr)
- [x] Nytt møte neste fredag (9/9/2016) @ivarconr
- [x] Oppdatere confluence siden  (@ivarconr)
- [x] Velkommen presentasjon (Hvorfor Node, BFF, async, non-blocking io, non-threading, universal)  (@ivarconr)
- [x] Intro til "learn-you-node" oppgavene  (@ivarconr)
- [x] Oppsummere learn-you-node (gå igjennom noen av de vanskelige oppgavene)  (@ivarconr)
- [x] Intro til "How to npm" (@sslash)
- [x] Oppsummering (@sslash)
- [x] Lage en Kahoot exam @sslash @ivarconr, @sveisvei @lagben 
- [x] Lage feedback-skjema. @ivarconr
- [x] Lage en liten oppsettett av vs-code guide! @sveisvei 
- [x] Developer setup (eslint + conf, editorconfig, etc) @sveisvei 
## Lengre oppgave etter lunsj

Ansvarlige: Sveinung, Benjamin

Oppgavene bør legge opp til dependency injection.
- [x] Intro til "readline" @ivarconr @sveisvei  
- [x] Intro til Express @lagben 
- [x] Intro til rabbitMQ/queue-løsning (maks 2 slides) @ivarconr
- [x] Intro til event-emitter @sveisvei 
- [x] Intro til Promiser @ivarconr
- [x] Check that rabbitmq works with ngrok! @ivarconr
### Task 1: Make a "Console Chat"

(Provided: Client connecting to Queue, and Message format used)

Deltakerene skal lage en "console" app som printer meldinger som allerede finnes på køen og gjør det mulig å skrive en melding som postes tilbake til køen. 

**Key results:**
- Nye meldinger  printes ut
- Skal være i stand til å sende nye meldinger
### Task 2: My first express app

TODO:
- [x] Provide test in task-2c (what else needs to be provided?)
- [x] Error handling 

Deltakerne skal sette opp sin første lille express-webapp. View teknologien er mustache og målet er at man skal kunne rendre et view og håndtere form-posts. 

**Key results:**
- Printe hello world
- Rendre et mustache view
- Route for å håndtere POST (navn + melding)
- Teste appen vha "supertest"
### Task 3: Connect express app with chat queue

Nå skal deltakerne koble sammen det de gjorde i oppgave 1 og oppgave 2. Målet er å få en chat-webapp som kobler meldinger fra alle deltakerne sammen. 

**Key results:** 
- Vise nye meldinger på en nettside
- Kunne poste nye meldinger til køen
- Forstatt kunne teste appen på en ok måte.
- Optional: lag en pakke, bruk npm link for å dra den inn
- Optional: Server Sent Events eller WebSockets eller lignende for real time oppdatering av meldinger
## Kahoot exam

Vi avslutter med en liten kahoot eksamen hvor deltakerne testes i sine tillærte node kunnskaper.

**Comment by sveisvei** [comment]
Vi burde vel legge til noe rundt `sikkerhet` og npm, og ikke stole blint på 3.part kode.

**Comment by phillipj** [comment]
Dette ser veldig lovende ut gutta :clap:
