### ISSUE TITLE
Todo 10.10.2016

### ISSUE THREAD

**Issue by ivarconr** [ivarconr/ws-node-intro#2]
- [x] Lag en tidsplan for hele workshoppen
- [x] Gå igjennom alle presentasjoner, ta **tiden** det tar
- [x] Øv på presentasjonen.
- [x] Gå igjennom alle node-school oppgaver. Snakke om hva som evt er utfrodringe med dem. 
- [x] Korrektur av oppgavesett
- [x] Gå igjennom alle oppgaver. Gjør et grovestimat over hvor lang tid ting bør ta og når vi pusher folk fra task 1 til task 2 osv.
